### ISSUE TITLE
Code: Remove deprecated code

### ISSUE THREAD

**Issue by bsesic** [Theophilix/event-table-edit#1]
We are currently having joomla 3.4.x.
The code for the plugin is not up to date and uses deprecated code. Therefore the component uses the legacy mode, which could cause errors.
Mainly the deprecated code is [JRequest](https://api.joomla.org/cms-3/classes/JRequest.html).
We need to upgrade the whole system replacing the deprecated code.

**Comment by Theophilix** [comment]
I replaced  "$app = JFactory::getApplication()->input;" with
"$app->get('variable');" and "$main  = JFactory::getApplication()->input;" with "$vName =     $main->get('view', '');"
