### ISSUE TITLE
demo site: can not access components

### ISSUE THREAD

**Issue by GudrunRau** [Theophilix/event-table-edit#114]
Hi, I would love to test the administration of your plugin. But ..
![grafik](https://user-images.githubusercontent.com/40494973/41897174-e0bd51fe-7926-11e8-8557-9b698b2ca3b8.png)
I cannnot access components (and extensions) to see how you did the table with appointment function. I think your plugin is exactly what I was searching for, but  Idon't find any information how to set up a table with appointments.
Thanks for your help.

**Comment by Theophilix** [comment]
Hello,
I fixed the problem.

**Comment by GudrunRau** [comment]
Thank you
