### ISSUE TITLE
Sortierung einer Tabelle

### ISSUE THREAD

**Issue by hofmar2** [Theophilix/event-table-edit#127]
Hallo,

ist es möglich das beim Aufruf einer Tabelle direkt eine  bestimmt Spalte nach Datum sortiert wird?

Bisher ist es so das der Seitenbesucher immer die Sortierung anklicken muss. Das ist nicht viel Arbeit, aber es führt bei manchen zu Problemen da die nicht verstehen das sie diesen Schritt noch ausführen müssen. Schön wäre eine direkte Sortierung der Spalte. 

Gruß
Markus

**Comment by Theophilix** [comment]
Hallo Markus,

eine solche Funktion wäre durchaus sinnvoll. Man könnte im Backend die Option "Sortierung bei Tabellenaufruf" und als Auswahl die entsprechende Spalte anbieten.
Es wird jedoch ca. 1 Monat dauern, bis ich dazu komme. 
->https://github.com/Theophilix/event-table-edit/issues/128

**Comment by hofmar2** [comment]
Hallo Theophilix,

das wäre super wenn du die Funktion einbauen könntest...

Wir haben gestern bei uns auf der Seite noch die Popups vergrößert welche sich beim bearbeiten von Tabellen öffnen. Weiß nicht ob das auch für die nächste Version Interessant ist. 

/*Popup vergrößern welches sich beim bearbeiten von Tabellen öffnet*/
#etetable-popupText {
    width: 600px;
    height: 300px;
}

textarea#etetable-inputfield {
    width: 575px;
    height: 250px;
}
