### ISSUE TITLE
Frontend / Backend: Enable sorting when the browser loads the table

### ISSUE THREAD

**Issue by Theophilix** [Theophilix/event-table-edit#128]
We should add an option to the backend called "Enable automatic sorting" [ger: "Automatische Sortierung aktivieren"] with yes / no [ger: ja / nein]. If the user chooses "yes", he sees a dropdown menu (title: "sort by" [ger: "Sortieren nach") and can choose the name of the table's columns (column1, column2 etc.).

The code should be like:
"After each editing action - if automatic sorting is on, then sort by selected column and save this as new order to mysql."
We could reload the table completely after each editing action BUT: this might slow down the table's speed extremely, if several users edit a table.

**Comment by hofmar2** [comment]
Hallo Theophilix,

hast Du so spontan eine Idee in welcher PHP-Datei ich die Abfrage finde? Habe da jetzt schon mehrere Stunden gesucht aber irgendwie ohne Erfolg.

Also in irgendeiner Datei muss ja eine Abfrage stehen wie z.B.

```
SELECT CONCAT(\'head_\', a.id) AS head, datatype FROM #__eventtableedit_heads AS a' .
					' WHERE a.table_id = ' . $this->id .
					' ORDER BY a.ordering ASC' .

```

Und da könnte ich dann ja das "ORDER BY" ändern oder?

Gruß
Markus

**Comment by Theophilix** [comment]
Müsste event-table-edit\site\models\etetable.php, Zeile 335 bzw. 384 sein.

**Comment by hofmar2** [comment]
Super funktioniert. :-) 
Habe in der Funktion "getRowsQuery()" 
`if ($tid == '14') {
			$orderCol = 'head_62';
			$orderDirn = 'ASC';
}
$query->order($orderCol.' '.$orderDirn);
`
eingefügt. 

Gruß
Markus

**Comment by Theophilix** [comment]
Fixed in 4.7.3 version
