### ISSUE TITLE
Update bbcode parser

### ISSUE THREAD

**Issue by Theophilix** [Theophilix/event-table-edit#136]
Our parser dates from 2004-2008, it is from Christian Seiler. 
We could use this lexical string parser: https://github.com/milesj/decoda.

**Comment by thunderer** [comment]
@Theophilix I would like to suggest my own Shortcode library: https://github.com/thunderer/Shortcode. This is a modern, very fast, most feature-complete, actively maintained, and one of the most popular shortcode / BBCode library in PHP ecosystem. I'm happy to answer any questions and discuss feature requests. Let me know how can I help.

**Comment by Theophilix** [comment]
Thank you for your suggestion, but it is too overloaded for my simple joomla plugin. I want to keep ETE small and simple. Decoda ist the best solution here.

**Comment by Theophilix** [comment]
Fixed in 4.8.4 version.
