### ISSUE TITLE
The date is not displayed correctly

### ISSUE THREAD

**Issue by f24nz** [Theophilix/event-table-edit#139]
When editing a date, the frontend table always shows 1970-01-01, in the database it is stored correctly though.

**Comment by Theophilix** [comment]
Which PHP / ETE version do you use? I can not reproduce this error on  demo.eventtableedit.com...

**Comment by f24nz** [comment]
PHP 7.2.14
ETE  4.7.4

**Comment by Theophilix** [comment]
Which date format do your dates have?

**Comment by f24nz** [comment]
Normally I use the format %a, %d.%m.%Y, but I have tried it with different formats too.
The format itself is always represented correctly though

**Comment by Theophilix** [comment]
I tried to reproduce your problems on my test website (http://test.eventtableedit.com/index.php/new-table) but I could not find an error, I downloaded 4.7.4 version and use PHP 7.1.23.
You could try to go back to 4.7.3 version (https://github.com/Theophilix/event-table-edit/releases/tag/4.7.3), or uninstall and reinstall 4.7.4. Don't forget to clean up your mysql table.
What is your browser and which version do you use?

**Comment by Theophilix** [comment]
You could try to go back to 4.7.3 version (https://github.com/Theophilix/event-table-edit/releases/tag/4.7.3), or uninstall and reinstall 4.7.4. Don't forget to clean up your mysql table.

**Comment by Theophilix** [comment]
xz

**Comment by twinbits3D** [comment]
I have the same problem with the date! Running on PHP 7.2 on joomla 3.9.4 . Can't understand what's going on. On an old table it's possible to use the date field correctly. If I setup an new table with the date field, it displays on all rows 1970-01-01 .

**Comment by Theophilix** [comment]
I can reproduce this error. For a quick fix: 
a) use 4.6.6 version
b) use text as datatype
c) Import your data via csv
Check, if there is an empty space in your date.
It seems like a change in Joomla PHP causes this. I need a few days to find the error. I have not much free time left these days.

**Comment by Theophilix** [comment]
I fixed the error now. It was a date conversion problem in helpers/etetable.php. Check my latest commit.

**Comment by twinbits3D** [comment]
Thank you for your work.
Wish you a nice weekend!
