### ISSUE TITLE
extension for Dropdown fields Yes/No in the table

### ISSUE THREAD

**Issue by JoeTerminal** [Theophilix/event-table-edit#140]
Is there a way to extend the default dropdown fields for Yes/No so that there is another way, such as "maybe" with a corresponding icon! The field should then jump to the next value with every click and display the respective icon. Is it planned to integrate this extension into a release by default?

**Comment by Theophilix** [comment]
Hello, 
we have that function already: Please check the "four state" column  in the demo: demo.eventtableedit.com.
