### ISSUE TITLE
Backend: CSV Import: Overwrite table or append does not work, there is a popup instead

### ISSUE THREAD

**Issue by sharpboy2008** [Theophilix/event-table-edit#146]
A popup asks the user: 'please enter a name for the table'

**Comment by Theophilix** [comment]
You are right, this is a big bug. I will fix it soon.

**Comment by Theophilix** [comment]
Fixed with newest commit. https://github.com/Theophilix/event-table-edit/commit/96f69e4f18fabfbf251adf2083e15fb1fd96c204
