### ISSUE TITLE
Alte Version von Event-Table-Edit / Old Event Table Edit versions

### ISSUE THREAD

**Issue by wobodi** [Theophilix/event-table-edit#147]
Ich benötige eine alte Version von Event-Table-Edit, die unter Joomal 2.5.28 / PHP 5.3.29 läuft. Wo finde ich die?

**Comment by Theophilix** [comment]
Was funktioniert denn mit der neuesten Version nicht (mehr)?

Du kannst hier: https://github.com/Theophilix/event-table-edit/releases?after=v.4.4.3 die ältesten Releases sehen und herunterladen.

**Comment by Theophilix** [comment]
[com_eventtableedit 4.2.zip](https://github.com/Theophilix/event-table-edit/files/3282793/com_eventtableedit.4.2.zip)
Hier noch eine ganz alte Version vom 29.09.2016, die noch aus Zeiten vor Github stammt.

**Comment by wobodi** [comment]
Ich habe den Inhalt einer Tabelle komplett gelöscht, um neue CSV-Daten zu importieren. Der Import klappte, jedoch wurden die Daten nicht in die Datenbank geschrieben. Somit war die Tabelle weiterhin leer. Eine manuelle Eingabe von Daten klappte auch nicht. Ich habe daraufhin die Komponente deinstalliert. Und nun fehlt mir die für Joomla passende Version.
