### ISSUE TITLE
normal table, no entries possible in frontend

### ISSUE THREAD

**Issue by sta-leipzig** [Theophilix/event-table-edit#156]
Hello, I want to create a table that the users can add to. After a single entry, the "hourglass" appears permanently. The table can only be reached with registration. Authorizations are set. What do I do wrong ? Where can I send you access data to check my settings? Joomla! 3.9.13 , Event-Table edit 4.8., php 7.3.12, (also tested with 7.2)

If it is possible, please log on to the homepage. I unlock you with all rights.

https://fechten-leipzig.de/organisation/bestellschein-innofence

A beautiful 3 Advent
Steffi Albrecht

**Comment by Theophilix** [comment]
Hello,

did you check that all authorization settings are ok? I can not reproduce the error in my test system... Did you try other browsers? Please  also check cache settings in Joomla. Furthermore, try to remove ETE completely with all MySQL data and reinstall it. And last but not least, check your datatypes.

**Comment by Theophilix** [comment]
This does not seem to be an issue anymore ->closed.
