### ISSUE TITLE
Joomla 9.3.14 issue on front end: no changes accepted

### ISSUE THREAD

**Issue by quantenion** [Theophilix/event-table-edit#162]
After update to Joomla 9.3.14 and ETE4.8.1 the AJAX changes on the frontend of my Joomla site doesn't work anymore.
I tried to reinstall the extension without effect.

**Comment by Theophilix** [comment]
Which changes don't work? Which PHP Version? Appointment or normal table? Did you verify the ACL settings? Please give more details, a screenshot or something.

**Comment by quantenion** [comment]
Example page: http://schkap.de/ete
Normal table, first column type is four-state, the others are text. Unregistered users are allowed to change the values.
![image](https://user-images.githubusercontent.com/59623855/71963756-9df7be00-31fc-11ea-9f83-88e94c5ddbbb.png)

PHP 7.2.26
mysql 5.5.60-0+deb7u1-log

EDIT:  I switched to PHP 7.4.1, still the same behaviour

**Comment by Theophilix** [comment]
Hello,
I can't reproduce your bug in my test environment (MySQL 5.7.28, PHP 7.3.11, Joomla! 3.9.14 Stable). Please try to uninstall ETE completely and ensure that all the folders and the mysql tables are deleted. Then reinstall ETE, create a new empty table (green button "new" and enter some data. Then please tell me if this works. If this works, you could check / change your Joomla cache settings or check your data for some wrong values.

**Comment by quantenion** [comment]
Solved:
I had somehow an override in my template for the component. After deleting this it works!
