### ISSUE TITLE
Dropdown cell empty box & new line issue

### ISSUE THREAD

**Issue by quantenion** [Theophilix/event-table-edit#165]
I experience some issues on my site:
- custom drop down fields don't work. An empty box appears, and the site "hangs up"
- When adding a new line, the site doesn't refresh automatically and "hangs up", after refreshing with F5, the new line appears.
- Minor: After clicking on a text cell to edit it, in previous versions the curser was focused on the appearing box and you could type directly. Not so anymore?

You can try the behaviour here: http://schkap.de/test
PHP 7.3, Joomla 3.9.15

**Comment by Theophilix** [comment]
>When adding a new line, the site doesn't refresh automatically and "hangs up", after refreshing with >F5, the new line appears.
 I can not reproduce this error on my test website.

>custom drop down fields don't work. An empty box appears, and the site "hangs up"
 I will fix this. Check new issue.
>Minor: After clicking on a text cell to edit it, in previous versions the curser was focused on the >appearing box and you could type directly. Not so anymore?
I will fix this. Check new issue.
