### ISSUE TITLE
Undefined property Joomla 3.9.21 with ETE 4.8.1

### ISSUE THREAD

**Issue by xImrahilx** [Theophilix/event-table-edit#171]
Hallo,

ich habe heute Joomla und ETE aktualisiert. Nun bekomme ich noch folgende Fehler:

Notice: Undefined property: stdClass::$automate_sort in /var/www/web382/html/VB2/components/com_eventtableedit/models/etetable.php on line 391

Notice: Undefined property: stdClass::$automate_sort in /var/www/web382/html/VB2/components/com_eventtableedit/models/etetable.php on line 391

Das wäre der Teil hier:
if ($this->_item->automate_sort) { 
			//$order_dir = explode(",",$this->_item->automate_sort_column);
			//$orderCol = $order_dir[0]; $orderDirn = $order_dir[1];

Notice: Undefined property: stdClass::$standardlayout in /var/www/web382/html/VB2/components/com_eventtableedit/views/etetable/tmpl/default_table.php on line 99

Das wäre der Teil hier:
$tmodes = ($this->item->standardlayout) ? $this->item->standardlayout : $switcher_enable;

 Undefined property: stdClass::$scroll_table in /var/www/web382/html/VB2/components/com_eventtableedit/views/etetable/tmpl/default.php on line 261

Das wäre der Teil hier:
if($this->item->scroll_table){ 

Im Admin Bereich unter Normale Tabellen --> Tabelle auswählen -> Tabelleneigenschaften

Automatische Sortierung nach Editierung aktivieren
Notice: Undefined property: Joomla\CMS\Object\CMSObject::$automate_sort in /var/www/web382/html/VB2/administrator/components/com_eventtableedit/views/etetable/tmpl/edit.php on line 201
aria-invalid="false">
Ja
Notice: Undefined property: Joomla\CMS\Object\CMSObject::$automate_sort in /var/www/web382/html/VB2/administrator/components/com_eventtableedit/views/etetable/tmpl/edit.php on line 227
checked="checked" aria-invalid="false">
Nein

Vielleicht kann das einmal geprüft werden. Danke!

Viele Grüße,
Christian

**Comment by xImrahilx** [comment]
Bisher hatte ich Version 4.5 eingesetzt. Mit 4.6 kam die Option 4 Auswahlmöglichkeiten dazu. Darüber war ich super dankbar. Aber seit der Version können Android User die Felder in den Tabellen nicht mehr bearbeiten. Unter Version 4.6 und 4.7 kommt ein Textfeld anstatt der Haken/Kreuz/etc und unter 4.8.1 kann kein Feld mehr bearbeitet werden. Ist hier etwas bekannt? Mir bleibt jetzt nur auf die Version 4.5 zurückzugehen.

**English:** Up to now I had used version 4.5. With 4.6 the option 4 choices were added. I was very happy about that. But since that version Android users can no longer edit the fields in the tables. In version 4.6 and 4.7 a text field comes instead of the check sign/cross/etc and in 4.8.1 no field can be edited anymore. Is anything known here? I have to go back to version 4.5 now.

**Comment by Theophilix** [comment]
Ich schaue mir das mal an.

**Comment by Theophilix** [comment]
Rückfrage: Welche PHP-Version, welche Joomla-Version, welcher Browser? Wurde geprüft, ob in der MYSQL-Tabelle noch Reste von ETE waren? Hast du einmal probiert, eine neue Tabelle aufzusetzen? Mir scheint, dass hier ein Problem mit dem Überschreiben von alten Werten in der MYSQL-Tabelle vorliegt (alte Funktion vs neue Funktion, eventtableedit_details).
Lösungsmöglichkeit:
- Tabellendaten als CSV exportieren und irgendwo speichern
- Prüfen ob alte Reste von ETE in deiner Joomla MySQL stehen und diese löschen
- ETE deinstallieren und neu installieren
- CSV wieder importieren

**English:** Possible solution:
- Export table data to CSV and save somewhere
- check MYSQL table for old ETE entries and delete them
- uninstall ETE and reinstall it
- import your csv

**Comment by xImrahilx** [comment]
Hallo, danke für dein Feedback und Anregungen. Ich habe jetzt die Komponente deinstalliert und nochmal mit 4.8.4 neuinstalliert. Damit scheint nun alles zu klappen. Die Fehler sind weg und auf 6 Endgeräten (IOS, Android 8, 9, 10, Laptop Win 10) konnte ich erfolgreich testen. Danke!

English: I uninstalled the component and reinstalled 4.8.4 version. The errors are gone now and all checks (IOS, Android 8, 9, 10, Laptop Win 10) were successful.

**Comment by Theophilix** [comment]
Sehr gut! 
Very good!
