### ISSUE TITLE
Bearbeitung im FE nicht möglich / Can't edit data via frontend

### ISSUE THREAD

**Issue by BirgerMonkey** [Theophilix/event-table-edit#174]
Hallo,

folgende Situation J3.9.22 und ETE4.8.6.
Auf zwei Seiten konnte ich in dieser Konstellation keine Felder bearbeiten oder eine neue Zeile hinzufügen. Auf mehr Seiten nutze ich diese Komponente nicht.
_On my two websites (Joomla 3.9.22 and ETE 4.8.6), I couldn't edit cells or add new rows._

Bei einer Seite habe ich ein Backup vom 30.09 eingespielt mit J3.9.21 und ETE 4.8.1 und es funktionierte auch mit dem Update auf J3.9.22 (auf das erneute Update auf ETE4.8.6 habe ich bislang verzichtet). 

_On one website, after loading a backup, ETE 4.8.1 worked with J3.9.22._

Bei einer anderen Seite konnte ich auch bis Ende August zurückgehen, aber es funktioniert nicht mehr.

Leider verstehe ich nicht alle Meldungen hier auf Github.

Benötigst Du noch Infos oder ist das Problem bekannt?

Besten Dank vorab.

Birger

**Comment by Theophilix** [comment]
Hallo, 

ich kann das Problem auf meinem Testsystem (Joomla 3.9.22 and ETE 4.8.6, PHP 7.3.22) nicht reproduzieren.
_On my test system I couldn't reproduce the error._
Alles was ich empfehlen kann ist: Alle Daten sichern als CSV und XML. Dann ETE deinstallieren. Evtl. prüfen, ob in der MYSQL-Tabelle noch Reste sind (kommt eigentlich äußerst selten vor). Dann die neueste (!) ETE-Version herunterladen und installieren.
_The only thing I can suggest: save all data as csv and xml. Then uninstall (in case check whether there is some old data remaining in MYSQL-tables) and reinstall newest ETE_

Gruß Theophilix

**Comment by BirgerMonkey** [comment]
Hallo Theophilix,

vielen Dank für die schnelle Antwort.
Über diesen Weg hat es einwandfrei funktioniert und ging auch sehr schnell.
_Now everything works well._
Danke noch einmal für diese tolle Erweiterung.

Wünsche Dir ein schönes Wochenende

Birger
