### ISSUE TITLE
Fehler 1054 - Unknown column 'corresptable' in 'field list'

### ISSUE THREAD

**Issue by DennisMenger** [Theophilix/event-table-edit#186]
Hallo. Ich bekomme bei der Anlage einer Tabelle für Termine einen Fehler.

1054 Unknown column 'corresptable' in 'field list' 
/var/www/virtual/tennisfreunde-kollow.de/neu_tennisfreunde-kollow_de/htdocs/libraries/joomla/database/driver/mysqli.php:668

Kann jemand helfen?

**Comment by DennisMenger** [comment]
Habe gerade gesehen, dass dieses Fehler auch produziert wird beim Anlagen einer normalen Tabelle.

Nutze die aktuelle Version 4.8.7

**Comment by Theophilix** [comment]
Couldn't reproduce the error (PHP 7.3.26, Joomla! 3.9.25 Stable, ETE 4.8.7). Please save and export your data to xml (or: csv) and uninstall ETE (ensure that alle ETE entries in your mysql table have been deleted). Then reinstall ETE.
Konnte den Fehler nicht reproduzieren. Bitte Daten sichern als CSV oder XML und ETE deinstallieren (ggf. prüfen ob alle ETE-Einträge auch wirklich aus der MySQL-Datenbank gelöscht wurden). Dann ETE neu installieren.

**Comment by DennisMenger** [comment]
ETE deinstalliert und neu installiert. Neue Tabelle anlegen funktioniert jetzt.

Aber seit Version 4.8.6 Fehler im Frontend. Siehe: http://www.neu.tennisfreunde-kollow.de/index.php?option=com_content&view=article&id=481:projekte-mitglieder&catid=10:aktuelles

Mit der Version 4.8.5 funktioniert noch alles.

**Comment by Theophilix** [comment]
Merkwürdig. Bitte, wenn möglich, andere Tabellendaten testen (neue CSV aufsetzen und importieren). Der Fehler sieht nicht so aus als läge es an ETE. Die PHP-Dateien sind nicht von ETE. Welche PHP und Joomla-Version? Es sollte die neueste sein (s.o.).
Ich kann ansonsten noch anbieten, Ihre Tabellendaten auf meinem Testsystem zu testen.
Strange. Please use other table data (import new CSV-file with your data). This error does not seem to have its origin in ETE. Those PHP-files are not ETE's files. Which PHP and Joomla version? It should be the newest. At last, I can offer you to test your table data on my test system.

**Comment by DennisMenger** [comment]
Nutze auch PHP 7.3.26 und Joomla 3.9.25.

Die Anzeige der Tabellen aus ETE hat auch immer funktioniert. Jetzt aktuell habe ich alle Tabellen gelöscht und ETE deinstalliert. Dann funktioniert auch die Verlinkung und Anzeige von der Startseite aus.

Installiere ich jetzt wieder die neueste Version von ETE, dann funktioniert die Verlinkung bzw. Anzeige von der Startseite aus nicht mehr. Aktuell habe ich keine Tabelle in ETE angelegt oder importiert.

**Comment by DennisMenger** [comment]
Es scheint wohl irgendwas mit dem E-Mail-Icon zu tun zu haben. Wenn ich die Anzeige des E-Mail-Icons in den Beiträgen deaktiviere funktioniert die Anzeige, auch wenn ETE installiert ist. Aktiviere ich es und ETE ist installiert, dann geht es nicht.

Keine Ahnung wie das zustande kommt.

**Comment by Theophilix** [comment]
Was für ein E-Mail-Icon? Welche Beiträge? Das hat nichts mit ETE zu tun, oder?

**Comment by DennisMenger** [comment]
Ja und Nein.

Man kann bei den Beiträgen auswählen, ob man sich ein E-Mail-Icon zum Teilen per Mail anzeigen lassen will. Irgendwie scheinen sich die beiden Sachen sich nicht zu vertragen. Bekomme dann den Fehler 500 JHtmlIcon::email not found

**Comment by Theophilix** [comment]
This is a problem of Joomla, not of ETE.
