### ISSUE TITLE
Large Data Sets

### ISSUE THREAD

**Issue by MassEast** [Theophilix/event-table-edit#188]
First of all, thank you so much for making this Joomla component publicly available for free. It seems to be able to do exactly what I am looking for.

I am currently running into huge performance issues: I imported a ~6300 rows csv file and the site on which I put the table takes **minutes** to load.

Pagination is on, but that does not seem to help. After some research, I found out that [Tabulizer - Large Data Sets](https://www.tabulizer.com/index.php/demo/large-data) seems to be able to cope with such large tables:

> Tabulizer can support large data sets, by using a mechanism called data source caching with the server side feature enabled. All source data are eventually stored in a database table for faster filtering and retrieval. As server side feature when enabled, allows Tabulizer to display only the option of the table that's really needed, while keeping the rest of the table data on the server side. The following demo table contains 10,000 rows.

Is there any way to make ETE capable of dealing with such large tables? Or is it maybe already capable but I just didn't find out how?

Thanks!

**Comment by Theophilix** [comment]
Thanks you for your ideas. Event Table Edit has not been designed for tables larger than maybe 1000 rows. I have never tested it, though. In some months, after having finished more important bugs than this one, I can work on your issue. I am only a hobby programmer with a small time budget.

**Comment by MassEast** [comment]
Thank you very much for your answer! I guess I will try Tabulizer then, but will switch to a non-commercial method once available. Maybe I could also share code with you, which might help tackling this problem.

**Comment by MassEast** [comment]
Closed means it is now available resp. will be in Joomla 4 version? Thanks!

**Comment by Theophilix** [comment]
Well, the migration to Joomla 4.0 and PHP 8 will cost a lot of time and money (I hire freelancer programmers to help me). It will take half a year. I will try to integrate large data sets, but I can't promise it.
