### ISSUE TITLE
1064 SQL Error on front end administer edit

### ISSUE THREAD

**Issue by jonathan-2** [Theophilix/event-table-edit#19]
I love event table edit, always have, it's great and I'm so glad it's re-appeared for Joomla 3.x. However I have a problem! I installed the latest package and in the table I created, in the front end when I click the pencil icon to administer the table I get this 1064 SQL Error.  Editing of cells is good though. Any idea where I should seek help?

1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND d.published = 1' at line 3 SQL=SELECT d.name as tablename FROM #__eventtableedit_details AS d WHERE d.id = AND d.published = 1
Really hope you can help as this extension is so good!

Thank you in anticipation... Jonathan

**Comment by Theophilix** [comment]
Hello Jonathan,
This problem is well known. Please wait one more week,  when I am going to release the version 4.2.
Till then: Try to uninstall ETE, check your mysql-database for leftovers/clean it and reinstall ETE.

**Comment by Theophilix** [comment]
The problem: In the php-file changetable.php the code snippet  'TYPE=MyISAM' has to be replaced with 'ENGINE = MyISAM'.

**Comment by jonathan-2** [comment]
Thanks... I have uninstalled and re-installed etc. but it still gives a 1064 for me. Therefore I will wait until you have done the new version and try again.

Thanks for all your hard work... Jonathan

**Comment by jonathan-2** [comment]
Hello Theo,

The code snippet 'TYPE=MyISAM' does not exist in my changetable.php

I can wait for the new version though.

Thanks Jonathan
