### ISSUE TITLE
After Joomla upgrade "Unknown column 'a.normalorappointment' in 'where clause'"

### ISSUE THREAD

**Issue by pez222** [Theophilix/event-table-edit#191]
After migrating from Joomla 2.5 to 3.10 and updating the component, I get an error: Unknown column 'a.normalorappointment' in 'where clause'
What is to be done?

**Comment by Theophilix** [comment]
Reinstall ETE and import your tables via csv. This will work. You should also use the newest Joomla and PHP version.
