### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by Wikt0ri0** [Theophilix/event-table-edit#192]
Hi there,

I've worked with this extension some years ago and I'm very glad it still exists.
Unfortunately I can't remember how to put the table in the article, and there is nowhere any guide or tutorial.
So i would really appreciate your help. And maybe you could make a small "how to" page.  ;)

Wiktorio

**Comment by Wikt0ri0** [comment]
Nevermind, can't use it anyway.
Installing it broke my site immediately...  "JHtmlIcon::email not found."
Uninstalling it fixed the problem immediately...

**Comment by Theophilix** [comment]
This will be worked on in https://github.com/Theophilix/event-table-edit/issues/187.
