### ISSUE TITLE
Manual ordering of rows forbidden (Frontend administration))

### ISSUE THREAD

**Issue by pez222** [Theophilix/event-table-edit#193]
Shows numbers of rows in grey. Hovering shows forbidden sign. Can't reorder and save rows.

**Comment by Theophilix** [comment]
Please tell me which PHP and Joomla version you use. If possible, also MySQL/other Database.

**Comment by pez222** [comment]
PHP-Version | 7.4.23
Joomla!-Version | Joomla! 3.10.1 Stable [ Daraja ] 22-August-2021 16:41 GMT
Databaseversion | 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~focal-log - utf8mb4_general_ci

**Comment by Theophilix** [comment]
There won't be any new ETE version based on Joomla 3.x. I have to rebuild ETE from scratch for Joomla 4. This will take half a year as I am only a hobby programmer.
