### ISSUE TITLE
Error: JSubMenuHelper

### ISSUE THREAD

**Issue by softstein** [Theophilix/event-table-edit#194]
Installing the component on a freshly installed 4.0.3 results in an error
Error: JSubMenuHelper not found.

Perhaps I got it wrong as "...Joomla 3.x and above" where "above" does not mean version 4.x ?
If this were the case this bugreport is void
<img width="464" alt="Screenshot 2021-09-30 at 16 02 51" src="https://user-images.githubusercontent.com/6675234/135470817-68b3b776-af49-44d9-a6be-56c70b7683c7.png">
.

**Comment by Theophilix** [comment]
Which PHP version? 
Seems you are right and my plugin is not compatible with Joomla 4.x yet. I am working on it.

**Comment by softstein** [comment]
I was using 7.4.12.
Thank you for looking into it!
