### ISSUE TITLE
Tablesaw - mode-swipe for smart phones

### ISSUE THREAD

**Issue by jonathan-2** [Theophilix/event-table-edit#20]
Tablesaw issue on Event-table-edit- is it possible to have the mode-**swipe** when viewing on a smart phone? So that when the table is loaded on a smart phone you can see all columns without having to select them using the toggle switch and swipe left or right across the columns? Maybe by including the Tablesaw "Mode Switch"

Everything else now looking good so far.

Cheers Jonathan

**Comment by Theophilix** [comment]
Hello!
the layout mode switch is available already. Please Check version 4.2. In general, smartphone layout will be optimized. But first, sorting issues have priority.
