### ISSUE TITLE
Can't save row content without refreshing the page

### ISSUE THREAD

**Issue by develop-euro** [Theophilix/event-table-edit#22]
I'm using the new version with Joomla 3.4.7 and it seems to work fine. The only problem is, when I add a new row in the front view, if I write in any cell of this new row and hit save it won't work. The cell keeps empty. I have to refresh te page to make it work.

**Comment by Theophilix** [comment]
I will see what I can do. Looks complicated so it may take two weeks or so.

**Comment by jonathan-2** [comment]
Theo, I am using the new version with the latest version of Joomla (3.6.2) and I cannot replicate what develop-euro is experiencing. Their problem is not happening for me. Perhaps you might ask develop-euro to upgrade their Joomla to 3.6.2 and try again or perhaps it's a PHP issue...I have attached my hosts server "Setting.docx" showing the PHP version etc.! 

This is from my Joomla system Info: attachment
[Setting.docx](https://github.com/Theophilix/event-table-edit/files/524080/Setting.docx)

**Comment by Theophilix** [comment]
I can replicate the problem (see demo.eventtableedit.com, ETE 4.3 and Joomla 3.6.2, PHP 7.0,  you have to use the given login) . You have to reload browser after having created a new row. After you have done this, everything works perfectly.

**Comment by jonathan-2** [comment]
Thanks Theo,
I still cannot get the "Reihenfolge" column to show. I have even exported
the xml file from your demo site and imported it to my site and that does
not show the "Reihenfolge" column either. I have refreshed the browser
repeatedly and even deleted the browser history and cache... all with no
resolution.
I wonder.. does the demo site use the latest Joomla version?
Sorry to be a nuisance and interrupt your busy day!

Best regards
Jonathan

**Comment by Theophilix** [comment]
No problem, keep on asking! The goal is to improve ETE and remove bugs. The demo site uses the newest versions of php, joomla etc, see screenshot.
![versions](https://cloud.githubusercontent.com/assets/17642779/19327404/2799af56-90cf-11e6-9379-67cf33388e22.png)
Also in Internet Explorer 11.0.9 everything works.
