### ISSUE TITLE
No "Delete A Row" columns of red X's appears (even for superuser)

### ISSUE THREAD

**Issue by jonathan-2** [Theophilix/event-table-edit#23]
Sorry Theo... The **"delete a row" red X's** are not visible. I have checked the Access Rules and for Superusers all are set to "Allowed" including the "Delete" one.
As this is an editing function on the front end then maybe the problem is a TABLESAW issue?
And I have tried it with Chrome, Edge and Firefox and there are no red X's in those browsers.
Thanks Theo
Best regards
Jonathan

**Comment by Theophilix** [comment]
Thanks for your information. I am happy to be informed about any bug in ETE.
Please go to demo.eventtableedit.com, log in with user: admin-demo and pw: admin-demo.
Then you will see the column used to delete and sort rows.
I use the newest Firefox version. Note: the function is located in admin backend of each table. It is called "Additional row sorting and deleting column".

**Comment by jonathan-2** [comment]
Thank you Theo,

I fixed it...I had to export the table as an XML then uninstall the
component and also remove the old  ETE database tables... then re-install
and re-import the table...and all is now good.

Best regards
Jonathan

**Comment by Theophilix** [comment]
Very good.
