### ISSUE TITLE
Verbesserung: Zusätzlicher Wert "Vielleicht" für den Bolean-Datenyp / Enhancement: New value "perhaps" for boolean mode.

### ISSUE THREAD

**Issue by wobodi** [Theophilix/event-table-edit#25]
Der User hat, wenn die Tabellenzelle als Boolean eingestellt ist, die Möglichkeit, zwischen den Werten Ja der Nein zu wählen. Hier möchte ich auch noch die Möglichkeit des Wertes "vielleicht", dokumentiert durch ein Fragezeichen, anbieten.

Viele Grüße
Wolfgang (wobodi)

**Comment by Theophilix** [comment]
Translation  of Wolfgang's message for our english speaking users:
If the datatype is "boolean", a user can choose from the two values "yes" (green check mark) and "no" (red X). Here I would like to offer a new one: "perhaps" ([orange?] question mark).

**Comment by wobodi** [comment]
Ich habe ein Fragezeichen (siehe Anlage). Das habe ich irgendwann einmal mittels Google gefunden. Und soweit ich es noch weiß, war bzw. ist es nicht lizensiert.

 

Von: Theophilix [mailto:notifications@github.com] 
Gesendet: Montag, 28. November 2016 15:44
An: Theophilix/event-table-edit <event-table-edit@noreply.github.com>
Cc: wobodi <wolfgang.bollmann@kabelmail.de>; Author <author@noreply.github.com>
Betreff: Re: [Theophilix/event-table-edit] Ja (v)/Nein(x) & Vielleicht(?) (#25)

 

Eine gute Idee. Freue mich über jede Unterstützung des Projekts. Hast du bereits ein open source Fragezeichen - Icon im Blick?

**Comment by wobodi** [comment]
Hallo Theophilix,

ich habe mein Anliegen inzwischen wie folgt selbst gelöst:

components\com_eventtableedit\template\images
Icon "questionmark.png" (Fragezeichen) gespeichert

components\com_enventtableedit\helpers\etetable.ph p
Eingefügt in: public static function parseBoolean($cell)
Zeile 50: $cell = '<img src="' . JURI::root() . 'components/com_eventtableedit/template/images/questionmark.png">';
Zeile 51 auskommentiert

components\com_enventtableedit\helpers\popup.js
Geändert in: A pseudo constructor for changing the status of boolean fields
Zeile 51: aktivieren
Zeile 52: deaktivieren
Zeile 53: aktivieren
Zeile 57: aktivieren
Diese Funktion sieht dann so aus:
BuildPopupWindow.prototype.constructBoolean = function(status, cell, editedCell) {
this.cell = cell;
this.editedCell = editedCell;

// Decide what value the field has
if (status == 1) {
status = -1;
//status = 0;
} else if (typeof(status) == "undefined" || status == null || status == "") {
status = 0;
} else if (status == -1 || status == 0) {
status++;
} else {
status = 1;
}

this.inputValue = status;

this.sendData();
}

Der User hat die nun die Möglichkeit, zwischen den Werten Ja, Nein oder Vielleicht (dokumentiert durch ein Fragezeichen) zu wählen.
