### ISSUE TITLE
Frontend: Join both filters into one again, turn it into instant search, the filter has to accept single german "Umlaut" letters like "ä", "ö", "ü" 

### ISSUE THREAD

**Issue by webberrych** [Theophilix/event-table-edit#26]
The filter does not accept the ä ü ö. For Exemple, i search "Gebäude".

**Comment by Theophilix** [comment]
Thank you very much for reporting this bug. Any help in correcting this bug is apreciated.

**Comment by Theophilix** [comment]
Hmm... After some attempts, I couldn't reproduce this error. Any hints, webberrych?

**Comment by Theophilix** [comment]
Moved to new issue: https://github.com/Theophilix/event-table-edit/issues/151
