### ISSUE TITLE
Sorting by date field results in an error if date field is empty

### ISSUE THREAD

**Issue by ptar** [Theophilix/event-table-edit#28]
Test:
1. Use a date field to sort a table
2. Add a new line
3. On top, you'll see two error messages with "Notice: Undefined offset: 2 in ..." and "Notice: Undefined offset: 2 in [...] com_eventtableedit/views/etetable/tmpl/default_row.php on line 27"

Please fix it. TIA!

**Comment by Theophilix** [comment]
Fixed in version 4.4.1
