### ISSUE TITLE
Misc.: New three (in fact: four) state datatype

### ISSUE THREAD

**Issue by Theophilix** [Theophilix/event-table-edit#33]
In order to use ETE to schedule events, it would be great to have a new three state datatype (values "NULL", "0", "1", "2") called "tristate". NULL= empty cell, 0 = cross.png, 1 = tick.png, 2=question-mark.png
Notice: File is in latest commit already: site\template\images\question-mark.png
A solution is already offered here: https://github.com/Theophilix/event-table-edit/issues/25

**Comment by Theophilix** [comment]
Enhancement added in 4.6 version.

**Comment by Heimchen** [comment]
This is a great feature, thanks a lot for it.
When I use it with a new table after updating from 4.5, I have to enter a number instead of clicking through the states. But I've seen in demo, that clicking should be possible. Is there anything to consider?

**Comment by Theophilix** [comment]
Did you choose the correct datatype "four state"? Click on administrate table symbol and change it for the column.
