### ISSUE TITLE
Loosing mor than20 columns when editing

### ISSUE THREAD

**Issue by Heimchen** [Theophilix/event-table-edit#35]
Hi,
if I edit a table with more than 20 columns, the columns behind the 20th are deleted. Nevertheless it is possible to create more than 20 columns, but not to edit.
Also in the past the yes/no field had an empty state. This is very helpful for appointments so could you please reactivate it?
Regards,
Heimchen

**Comment by Theophilix** [comment]
Thank you very much for reporting this bug. Event Table Edit is not MS Excel :-) So we have certain limitations. But I will see what I can do.
I opened a new enhancement issue for your empty state wish.

**Comment by Theophilix** [comment]
I will reopen this as enhancement wish.

**Comment by Heimchen** [comment]
I don't need hundreds of columns, just 24. I use it for a little ensemble to plan appointments.
I'm an independent embedded software developer and expected that the problem should be quiet simple, like LIMIT 20 in SQL statement, but I did not find anything like this. Unfortunately I have no Joomla experience, web technologies is not my major discipline and I'm short in time... :-(

**Comment by Theophilix** [comment]
Your enhancement wish is already listed here: https://github.com/Theophilix/event-table-edit/issues/37.
Please be patient.
