### ISSUE TITLE
Text alignment with BBCode not working properly

### ISSUE THREAD

**Issue by bulli11** [Theophilix/event-table-edit#38]
Hi,
why the text alignment [left][/left] and [right][/right] as BBCode is not working?
Thanks in advance for an answer! :-)
BR

**Comment by Theophilix** [comment]
Did you activate the function in the table's settings?

**Comment by bulli11** [comment]
Yes,
i did.

Have a look to the screenshot. In the first line the center function is activated (the code is not visible). In line 2 and 3 left and right but it is not working.

![screenshot](https://cloud.githubusercontent.com/assets/24920462/21672561/83fa5700-d323-11e6-8b6d-29e18d812591.png)

BR
Bulli

 

 

 



 

 

Von: Theophilix [mailto:notifications@github.com] 
Gesendet: Mittwoch, 4. Januar 2017 22:23
An: Theophilix/event-table-edit <event-table-edit@noreply.github.com>
Cc: bulli11 <rainer@o2online.de>; Author <author@noreply.github.com>
Betreff: Re: [Theophilix/event-table-edit] Text alignment with BBCode (#38)

 

Did you activate the function in the table's settings?

**Comment by Theophilix** [comment]
Thank you for your information. I will see what I can do. Please be patient. There are other more important bugs to fix.

**Comment by Theophilix** [comment]
Fixed. Will be released in 4.4.4 Version.
