### ISSUE TITLE
Date input not possible after Joomla-Update to 3.7.0

### ISSUE THREAD

**Issue by MalikMoses** [Theophilix/event-table-edit#64]
Hello,
after updating Joomla from 3.6.5 to 3.7.0 The Input of date in a field for a calender-date does not work anymore.

By clicking on the date-cell in the table (frontend) the input-window Pops up together with an ever  Spinning Ajax-Icon an the Input window is frozen.
the only possible Action you could do is to delete the last date of the cell by clicking on "Entfernen" (Clear-button)

any hints how to fix that Error ?

see:
![date-input_eventtable](https://cloud.githubusercontent.com/assets/28355386/25669579/381ef9da-302a-11e7-85d1-4be4f5b08dd8.jpg)

**Comment by Theophilix** [comment]
Thanks for communicating this bug. I will see what I can do. It may take some days. Please change datatype to "text" until I have fixed this bug.

**Comment by MalikMoses** [comment]
It seems that I as well can not Change the column-field type ...
... if I click on "Save" in the frontend I get the Error-message:

1054 - Unknown column 'col' in 'field list'

**Comment by Theophilix** [comment]
Our problem seems linked to other Joomla calendar issues: https://github.com/joomla/joomla-cms/issues?utf8=%E2%9C%93&q=calendar. We'll have to wait for some bugfixes there.

**Comment by Theophilix** [comment]
Fixed in 4.5.4 version.
