### ISSUE TITLE
event-table-edit is not compatible with PHP-Version 7.0 and 7.1 ?

### ISSUE THREAD

**Issue by MalikMoses** [Theophilix/event-table-edit#65]
Warning: 
After updating der PHP-Version on the server from version 5.6 to 7.0 using Joomla 3.6.5
Event-Table-Edit was not working any more.

Trying to fill a field in the table (Frontend) results in PHP-Error-Messages written into the Table

**Comment by Theophilix** [comment]
Please post the error messages. 
You could try to uninstall ETE and delete all MYSQL entries and make a clean install.
And yes, there are problems with Joomla 3.7x, but  there shouldn't be with 3.6.5 and PHP 7.0 or 7.1 (see demo.eventtableedit.com, it works well with Joomla 3.6.5 and PHP 7.1)
Maybe your error reports are on the highest level.

**Comment by MalikMoses** [comment]
----------------------------------
Here are the Error messages, in fact only one Warning message several times, but very nasty.


At the top of the page shown I get:

`Warning: Declaration of EventtableeditModelEtetable::populateState() should be compatible with JModelList::populateState($ordering = NULL, $direction = NULL) in /www/htdocs/homepage/components/com_eventtableedit/models/etetable.php on line 15`


Filling in a cell of the table I get the same massage either in the Popup-Menue where I should type the text or the date, or in formated manner written in the Cell in case of list of choices:

<br />
<b>Warning</b>:  Declaration of EventtableeditModelEtetable::populateState() should be compatible with JModelList::populateState($ordering = NULL, $direction = NULL) in <b>/www/htdocs/homepage/components/com_eventtableedit/models/etetable.php</b> on line <b>15</b><br />
------------------------------

Both debugging options in Joomla are switched off, and I could not find any choice in the admin-menues to reduce the error-level not to show this warning.

I don't like to unistall ETE compltetly and delete all entries in the database as suggested,, because it will cost me many hours of work to fill in again all data manually in lhe tables created so far.

any Ideas for a work-around?

**Comment by Theophilix** [comment]
try this: in file site/models/etetable.php: delete the values in the parentheses at : "protected function populateState($ordering = NULL, $direction = NULL)", so you get: "protected function populateState()" Please reply if this does not work.

**Comment by MalikMoses** [comment]
Doing the exact opposite of your suggestion was successful :-))
I changed: `protected function populateState()`
to: `protected function populateState($ordering = NULL, $direction = NULL)`

Thank you for your support and for keeping Evet Table Edit alive !

**Comment by Theophilix** [comment]
Happy I could help you!
