### ISSUE TITLE
Frontend: Allow more than one table per page (mehr als eine Tabelle pro Seite)

### ISSUE THREAD

**Issue by Alexiandra** [Theophilix/event-table-edit#68]
I wish i could see more than one table on a site. Perhaps its possible to put tables in articles?

(Ich wünschte ich könnte mehr als eine Tabelle auf einer Seite haben. Ist es möglich das zu realisieren, indem man Tabellen in Beiträge einfügt?)

**Comment by Theophilix** [comment]
Hello,
this is possible. But there is no quick and dirty solution for this. We have to create a module from Event Table Edit (ETE). At the moment, there are many other bugs to fix. So your enhancement wish may take several months until it will be integrated into ETE.

**Comment by Theophilix** [comment]
Moved to https://github.com/Theophilix/event-table-edit/issues/160
