### ISSUE TITLE
Bug: Adding a new line in table not visable without clearing the browser-cache

### ISSUE THREAD

**Issue by MalikMoses** [Theophilix/event-table-edit#69]
After updating to Joomla 3.7.3 and EventTableEdit 4-5-4
Adding a new Line (clicking on the greeen +) to a table does not show up as new line.
After clearing the browsers cache and loading the page anew the added line appears.

**Comment by Theophilix** [comment]
Hello,
in the demo demo.eventtableedit.com/administrator (PHP 7.1, Joomla 3.7.3 and EventTableEdit 4.5.4),
login: admin-demo
password: admin-demo
I can't find any error. Please go to system -> global config -> server -> error reporting and change the setting to "development" and report the errors if you find some. Thank you.
