### ISSUE TITLE
Bug: Tables are no longer editable in the backend 

### ISSUE THREAD

**Issue by MalikMoses** [Theophilix/event-table-edit#70]
After updating to Joomla 3.7.3 and EventTableEdit 4-5-4

All existing tables can no longer be edited. Even without making any changes clicking on "save", "save and close", or "save and new" leads to the error message "Ungültiges Formular" ("invalid Form").

Creating a new table is possible but the new table as well can not be edited after saved once.

**Comment by Theophilix** [comment]
Hello,
in the demo demo.eventtableedit.com/administrator (PHP 7.1,  Joomla 3.7.3 and EventTableEdit 4.5.4),
login: admin-demo
password: admin-demo
I can't find any error. Please go to system -> global config -> server -> error reporting and change the setting to "development" and report the errors.

**Comment by MalikMoses** [comment]
If I set the error reporting to "Developer" or "Maximum" the behaveour is as follows:

calling "tables" in Menue in the backend results in the messages:
	
Notice: Undefined property: stdClass::$row in /www/htdocs/...website.../administrator/components/com_eventtableedit/views/etetables/tmpl/default.php on line 144

Notice: Undefined property: stdClass::$col in /www/htdocs/...website.../administrator/components/com_eventtableedit/views/etetables/tmpl/default.php on line 147


in the frontend I get the messages:

Notice: Undefined property: stdClass::$sorting in /www/htdocs/...website.../components/com_eventtableedit/views/etetable/tmpl/default_table.php on line 92

Notice: Undefined property: stdClass::$switcher in /www/htdocs/...website.../components/com_eventtableedit/views/etetable/tmpl/default_table.php on line 95


And very funny, when saving a table in the backend I get no error message when Error reporting ist set to either "Maximum or "developer" and I get the green-messages "Settings saved" (which is not true, because the changes will not show if I edit the Table the mext time) 
And I still get still the red-message "Error" plus the message "Wrong Form" in a window if I choose an other way of error reporting.

---------------------------
what I urgendly need to do is to set the additional column to delete Rows in the frontend. This Column disappeared after updating EventTableEdit so I want to set:

Zusatzspalte zur Umsortierung und zum Löschen der Tabellenzeilen
  X Anzeigen
  O Verbergen

But in the MySQL-Database I could not find any Entry to set the appropriate Flag from 0 to 1 in the table xyz_eventtableedit_details (no flag for "sort or delete" available)
And the database contains a row of data for a test-Table I ameanwhile already deleteted.

Might it be possible that during the update the database-layout did not get updated and the database got inconsistent? This problem maybe does not show up it I install everything again from scratch.

**Comment by Theophilix** [comment]
Hello,
which PHP Version do you use? I am very sorry, but I still can not reproduce the errors.
Please try so save your tables to XML or CSV. Then check  via PHPMYADMIN if there are some ETE entries left in your MYSQL-Table. Then reinstall ETE.
Thanks,
Theophilix
