### ISSUE TITLE
Hinzufügen einer weiteren Option "Leer"

### ISSUE THREAD

**Issue by Imrahil81** [Theophilix/event-table-edit#75]
Hallo,

danke für die Weiterentwicklung dieses tollen Tools. Ist es eventuell möglich eine weitere Option einzubauen? Wenn ich in eine Zelle klicke erscheint entweder der Haken (1. Klick) oder das Kreuz (2. Klick), ist es hier möglich die Zelle auch wieder zu leeren (3. Klick)? Aktuell habe ich das Problem, dass sich User meiner Seite in eine Liste eintragen sollen, ob sie bei einem Event dabei sind oder nicht. Manchmal verklickt sich jemand und setzt einen Haken oder Kreuz in der falschen Zeile bei einem anderen User. Den Eintrag bekommen die User selber nicht mehr heraus. Wäre doch gut, wenn sie das selber beheben können, ohne das ich die ganze Spalte löschen und neu anlegen muss.

Viele Grüße,

Christian Schulze

**Comment by Theophilix** [comment]
Danke für deinen Vorschlag. Ist schon länger in Planung: https://github.com/Theophilix/event-table-edit/issues/33
