### ISSUE TITLE
Caching interferes with edit rights

### ISSUE THREAD

**Issue by ptar** [Theophilix/event-table-edit#79]
If Joomla cache is enabled, the event table editing option doesn't switch with the login or logoff of a user, but only when the cache expires.

**Reproduce:** 
- Have an eventtable associated with a certain permission group to allow frontend editing for members of this group
- Check the eventtable with a user of this group logged in or off
- If it's not fitting the permission:
Clear the cache (general or com_eventtableedit only) 
- Re-load the page and check the permission again: Now it should fit

**Expected behaviour:**
Edit permission switches with the login status of the user

**Comment by Theophilix** [comment]
Thank you very much for reporting this bug. I will check.

**Comment by Theophilix** [comment]
Fixed in 4.6.1 version.
