### ISSUE TITLE
Frontend: Administer table save buttons leads to loss of data

### ISSUE THREAD

**Issue by wobodi** [Theophilix/event-table-edit#88]
Under "Manage Table", "Save" completely clears the "Text" column and resets all "Four Options" columns. The unmodified or deleted data should be preserved. Where is the mistake?

**Comment by Theophilix** [comment]
Why closed an reopened?

**Comment by Theophilix** [comment]
This could be due to some changes in the new Joomla version. I will check.

**Comment by wobodi** [comment]
It was not on purpose!!

 

Von: Theophilix [mailto:notifications@github.com] 
Gesendet: Montag, 12. Februar 2018 15:30
An: Theophilix/event-table-edit <event-table-edit@noreply.github.com>
Cc: Wolfgang Bollmann <wolfgang.bollmann@kabelmail.de>; State change <state_change@noreply.github.com>
Betreff: Re: [Theophilix/event-table-edit] Manage Table (#88)

 

Why closed an reopened?

**Comment by Theophilix** [comment]
Fixed in final release 4.6.2.
